GET http://localhost:8083/connectors/

###
GET http://localhost:8083/connectors/customer_outbox_connector/status

###
GET http://localhost:8083/connectors/order_outbox_connector/status

###
GET http://localhost:8083/connectors/inventory_outbox_connector/status