### Create Customer

POST http://localhost:9003/customers
Content-Type: application/json

{
  "username": "mirko",
  "fullName": "Mirko Mirkic",
  "balance": 250
}

> {%
    client.global.set("customer_id", JSON.parse(JSON.stringify(response.body)).id);
%}

### Get Customer
GET http://localhost:9003/customers/{{customer_id}}
Content-Type: application/json

### Create Product

POST http://localhost:9002/products
Content-Type: application/json

{
  "name": "banana",
  "stocks": 20
}

> {%
    client.global.set("product_id", JSON.parse(JSON.stringify(response.body)).id);
%}

### Get Product

GET http://localhost:9002/products/{{product_id}}
Content-Type: application/json


### Create Order

POST http://localhost:9001/orders
Content-Type: application/json

{
  "customerId": "{{customer_id}}",
  "productId": "{{product_id}}",
  "quantity": 2,
  "price": 20
}