version: "3.7"

services:
  orderdb:
    container_name: orderdb
    image: debezium/postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: on-failure

  customerdb:
    container_name: customerdb
    image: debezium/postgres:13
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: on-failure

  inventorydb:
    container_name: inventorydb
    image: debezium/postgres:13
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: on-failure

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:6.2.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://broker:29092
      LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  debezium-connect-1:
    container_name: debezium-connect-1
    image: debezium/connect:2.1.1.Final
    ports:
      - 8083:8083
    environment:
      GROUP_ID: groupA
      ADVERTISED_HOST_NAME: "debezium-connect-1"
      ADVERTISED_PORT: 8083
      CONFIG_STORAGE_TOPIC: debezium_connect_config
      OFFSET_STORAGE_TOPIC: debezium_connect_offsets
      STATUS_STORAGE_TOPIC: debezium_connect_status
      BOOTSTRAP_SERVERS: broker:29092
    depends_on:
      - broker
      - zookeeper

  debezium-connect-2:
    container_name: debezium-connect-2
    image: debezium/connect:2.1.1.Final
    ports:
      - 18083:8083
    environment:
      GROUP_ID: groupA
      ADVERTISED_HOST_NAME: "debezium-connect-2"
      ADVERTISED_PORT: 8083
      CONFIG_STORAGE_TOPIC: debezium_connect_config
      OFFSET_STORAGE_TOPIC: debezium_connect_offsets
      STATUS_STORAGE_TOPIC: debezium_connect_status
      BOOTSTRAP_SERVERS: broker:29092
    depends_on:
      - broker
      - zookeeper

  debezium-ui:
    container_name: debezium-ui
    image: debezium/debezium-ui:2.1.1.Final
    depends_on:
      - debezium-connect-1
      - debezium-connect-2
    ports:
      - "8050:8080"
    environment:
      - KAFKA_CONNECT_URIS=http://debezium-connect-1:8083,http://debezium-connect-2:8083

  kafdrop:
    image: obsidiandynamics/kafdrop:3.30.0
    container_name: kafdrop
    depends_on:
      - broker
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: broker:29092
